### ISSUE TITLE
Sunsaver script calls the wrong Python

### ISSUE THREAD

**Issue by pbitzer** [hamma-dev/mjolnir-hamma#2]
First line of sunsaver script has a tilde in the shebang line:

`#!~/dev/brokkrenv/bin/python`

This won't call the Python you want it to...

**Comment by CAM-Gerlach** [comment]
Doesn't `~` doesn't resolve to `/home/pi`? Not sure I quite understand, sorry.

The main issue here is that it depends on a few things from Brokkr, which means if I change the internals of the latter, the former breaks. You could refactor it to work again with Brokkr but better, I think, to just vendor them directly into the script so we don't have to worry about it breaking again in the future, its just one utility function and a few constants and in the long term I'll eventually integrate iut with Brokkr directly as a command plugin.

I'm happy to knock that out for you now, but if you'd rather take care of it, totally fine with me.

**Comment by pbitzer** [comment]
> Doesn't `~` doesn't resolve to `/home/pi`? Not sure I quite understand, sorry.
> 
> The main issue here is that it depends on a few things from Brokkr, which means if I change the internals of the latter, the former breaks. You could refactor it to work again with Brokkr but better, I think, to just vendor them directly into the script so we don't have to worry about it breaking again in the future, its just one utility function and a few constants and in the long term I'll eventually integrate iut with Brokkr directly as a command plugin.
> 
> I'm happy to knock that out for you now, but if you'd rather take care of it, totally fine with me.

Sorry, the issue wasn't completely clear. I was just going to take care of it. I'm pretty sure the shebang line doesn't do tilde expansion. I only noticed it since the script doesn't use the Python in `brokkrenv`.

**Comment by pbitzer** [comment]
Sure, we can open a new issue. We'll mark it pretty low on the priority list though...
