### ISSUE TITLE
Mount udisks filename

### ISSUE THREAD

**Issue by pbitzer** [hamma-dev/mjolnir-hamma#9]
@CAM-Gerlach Should the file https://github.com/hamma-dev/mjolnir-hamma/blob/master/files/mount-udisks.pkla have an hyphen (as it does now) or an underscore (as it is in some of the commands)?

**Comment by CAM-Gerlach** [comment]
@pbitzer Assuming you're referring to the filename, hyphen is the convention for these types of config files, (in this case, polkit rules), but the filename shouldn't matter, its purely for convenience. The system should load everything in the `/etc/polkit-1/localauthority` directory, including `50-local.d` where this goes. I'm a little confused what commands you're referring to, sorry? I'm not aware of any Brokkr, Linux or other commands that have this name, and a search of all the Mjolnir-related repos reveals no hits, underscore or hyphen. But perhaps I'm misinterpreting what you're asking and missing something silly?

**Comment by pbitzer** [comment]
This was lost-in-translation sort of problem. We had some commands refer to this file with an underscore instead of hyphen. It's all worked out now. Closing.
